### ISSUE TITLE
Recipes Overriding... (Not a Issue. Its a help)

### ISSUE THREAD

**Issue by Speiger** [asiekierka/AsieTweaks2#2]
I saw what you did in stream and saw you did a extremly derp error...
I did the exact same thing (maybe not as clean as you but stable enough and not without guessing.)

Here is my help: https://github.com/TinyModularThings/TinyModularThings/blob/1.6.4/Spmod_Common/Source/speiger/src/spmodapi/common/recipes/helper/RecipeOverrider.java

**Comment by asiekierka** [comment]
Fixed ages ago.
