### ISSUE TITLE
Idea for Modpack

### ISSUE THREAD

**Issue by Speiger** [asiekierka/AsieTweaks2#8]
Asie long time ago you asked me a way to make players eat often. I know you changed the FoodStats a little bit that people get often hungry.
Here is another idea:
Crafting makes hungry so as more people craft the more they get hungry. 
I made it like that per craft it makes the same hunger as breaking a block. (0.025)
0.025 * items needed to craft that item. So you get a balanced a little bit.
An example: (To craft 1 Stack Bookshelves (You have full hunger&Saturation)) makes you so hungry that you have 3 hunger left.

**Comment by Vexatos** [comment]
People actually get hungry much more slowly in this mod pack.
